---
foreman_apt_main_baseurl: "http://deb.theforeman.org/"
foreman_apt_main_release: 2.5
foreman_apt_main_os_version: "{{ ansible_distribution_release }}"
foreman_apt_main_gpg: 1
foreman_apt_main_key: "http://deb.theforeman.org/pubkey.gpg"

puppet_apt_main_deburl: "https://apt.puppet.com/puppet{{ puppet_apt_main_release }}-release-{{ ansible_distribution_release }}.deb"
puppet_apt_main_release: 6

foreman_apt_plugins_baseurl: "http://deb.theforeman.org/"
foreman_apt_plugins_release: 2.5
foreman_apt_plugins_os_version: plugins
foreman_apt_plugins_gpg: 1
foreman_apt_plugins_key: "http://deb.theforeman.org/pubkey.gpg"

foreman_yum_main_baseurl: "http://yum.theforeman.org/releases/latest/el{{ ansible_distribution_major_version }}/$basearch/"
foreman_yum_main_gpg: 1
foreman_yum_main_key: "http://yum.theforeman.org/releases/latest/RPM-GPG-KEY-foreman"

puppet_yum_main_baseurl: "https://yum.puppetlabs.com/puppet{{ puppet_apt_main_release }}/puppet{{ puppet_apt_main_release }}-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"
puppet_yum_main_release: 6

foreman_yum_ror51_baseurl: "https://copr-be.cloud.fedoraproject.org/results/@theforeman/tfm-ror51/epel-{{ ansible_distribution_major_version }}-$basearch/"
foreman_yum_ror51_gpg: 1
foreman_yum_ror51_key: "https://copr-be.cloud.fedoraproject.org/results/@theforeman/tfm-ror51/pubkey.gpg"

foreman_yum_plugins_baseurl: "http://yum.theforeman.org/plugins/latest/el{{ ansible_distribution_major_version }}/$basearch/"
foreman_yum_plugins_gpg: 1
foreman_yum_plugins_key: "http://yum.theforeman.org/releases/latest/RPM-GPG-KEY-foreman"

foreman_plugins_repo: true
foreman_ror51_repo: true
foreman_enable_service: false

foreman_db_adapter: postgresql
foreman_db_name: foreman
foreman_db_username: foreman
foreman_db_password: foreman
foreman_db_host: localhost
foreman_db_pool: 5
foreman_db_timeout: 5000

foreman_domain: "{{ ansible_domain }}"
foreman_fqdn: "{{ ansible_fqdn }}"
foreman_admin_password: foreman
foreman_admin_email: "admin@{{ ansible_fqdn }}"
