---
foreman_release: 2.5
puppet_release: 6
katello_release: 4.1

foreman_apt_main_baseurl: "http://deb.theforeman.org/"
foreman_apt_main_os_version: "{{ ansible_distribution_release }}"
foreman_apt_main_gpg: 1
foreman_apt_main_key: "http://deb.theforeman.org/pubkey.gpg"

puppet_apt_main_deburl: "https://apt.puppetlabs.com/puppet-release-{{ ansible_distribution_release }}.deb"

foreman_apt_plugins_baseurl: "http://deb.theforeman.org/"
foreman_apt_plugins_os_version: plugins
foreman_apt_plugins_gpg: 1
foreman_apt_plugins_key: "http://deb.theforeman.org/pubkey.gpg"

foreman_yum_main_baseurl: "http://yum.theforeman.org/releases/{{ foreman_release }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm"
foreman_yum_main_gpg: 0
foreman_yum_main_key: "http://yum.theforeman.org/releases/{{ foreman_release }}/RPM-GPG-KEY-foreman"

puppet_yum_main_baseurl: "https://yum.puppetlabs.com/puppet{{ puppet_release }}/puppet{{ puppet_release }}-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"

katello_yum_main_baseurl: "https://yum.theforeman.org/katello/{{ katello_release }}/katello/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/katello-repos-latest.rpm"

foreman_plugins_repo: true
foreman_enable_service: true

foreman_db_adapter: postgresql
foreman_db_name: foreman
foreman_db_username: foreman
foreman_db_password: foreman
foreman_db_host: localhost
foreman_db_pool: 5
foreman_db_timeout: 5000

foreman_domain: "{{ ansible_domain }}"
foreman_fqdn: "{{ ansible_fqdn }}"
foreman_admin_password: foreman
foreman_admin_email: "admin@{{ ansible_fqdn }}"
foreman_dns_forwarders: '8.8.8.8'

foreman_organization: ZTech
foreman_location: LabDC

foreman_net_interface: eth1
foreman_proxy_tftp: "true"
foreman_proxy_dns: "true"
foreman_proxy_dhcp: "true"
foreman_dhcp_start_ip: 192.168.100.3
foreman_dhcp_end_ip: 192.168.100.254