---
- name: template foreman database.yml
  template:
    src: database.yml.j2
    dest: /etc/foreman/database.yml
    backup: yes

- name: enable foreman service
  service:
    name: foreman
    enabled: yes
    state: started
  when: foreman_enable_service
