---
- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: install foreman-installer
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ foreman_pkg }}"

# - name: run foreman installer package
#   shell: "foreman-installer -s \
#           --foreman-admin-password {{ foreman_admin_password }}"
#   delay: 10

- name: install foreman plugins
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ foreman_plugins_pkg }}"
  when: foreman_db_adapter == "postgresql"

- name: run foreman installer to addtional plugins
  shell: "foreman-installer --scenario katello -s \
          --foreman-initial-organization {{ foreman_organization }} \
          --foreman-initial-location {{ foreman_location }} \
          --foreman-initial-admin-password {{ foreman_admin_password }} \
          --foreman-proxy-tftp={{ foreman_proxy_tftp }} \
          --foreman-proxy-dhcp={{ foreman_proxy_dhcp }} \
          --foreman-proxy-dhcp-interface={{ foreman_net_interface }} \
          --foreman-proxy-dhcp-gateway={{ ansible_default_ipv4.gateway }} \
          --foreman-proxy-dhcp-nameservers={{ ansible_eth1.ipv4.address }} \
          --foreman-proxy-dhcp-range='{{ foreman_dhcp_start_ip }} {{ foreman_dhcp_end_ip }}' \
          --foreman-proxy-dns={{ foreman_proxy_dns }} \
          --foreman-proxy-dns-interface={{ foreman_net_interface }} \
          --foreman-proxy-dns-zone={{ foreman_domain }} \
          --foreman-proxy-dns-forwarders='{{ foreman_dns_forwarders }}' \
          --foreman-proxy-dns-reverse=0.100.168.192.in-addr.arpa \
          --enable-foreman-proxy-plugin-discovery \
          --foreman-proxy-plugin-discovery-install-images=true"