---
- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- include: repository.yml
- include: installation.yml
- include: configuration.yml
