---
# Debian foreman apt key
- name: configure foreman apt key
  apt_key:
    url: "{{ foreman_apt_main_key }}"
    state: present
  when: ansible_os_family == "Debian" and foreman_apt_main_gpg

# Debian foreman apt repo
- name: configure foreman apt repository
  apt_repository:
    repo: "deb {{ foreman_apt_main_baseurl }} {{ foreman_apt_main_os_version }} {{ foreman_release }}"
    state: present
  when: ansible_os_family == "Debian"

# Debian foreman plugin apt repo
- name: configure foreman plugins apt repository
  apt_repository:
    repo: "deb {{ foreman_apt_plugins_baseurl }} {{ foreman_apt_plugins_os_version }} {{ foreman_release }}"
    state: present
  when: ansible_os_family == "Debian" and foreman_plugins_repo

# Debian puppet apt repo
- name: configure puppet apt repository
  apt:
    deb: "{{ puppet_apt_main_deburl }}"
    state: present
  when: ansible_os_family == "Debian"

# Redhat foreman yum repo
- name: configure foreman yum repository
  yum:
    name: "{{ foreman_yum_main_baseurl }}"
    state: present
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat"

# Redhat puppet yum repo
- name: configure puppet yum repository
  yum:
    name: "{{ puppet_yum_main_baseurl }}"
    state: present
  when: ansible_os_family == "RedHat"

  # Redhat katello yum repo
- name: configure katello yum repository
  yum:
    name: "{{ katello_yum_main_baseurl }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: configure additional repositories
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ foreman_extra_repos_pkg }}"
