---
# This playbook deploys foreman together with passenger_nginx and mysql
# including foreman-proxy, tftp and dhcp
- hosts: all
  become: true
  vars_files:
    - vars/example.yml
  roles:
    - { role: common }
    - { role: isc_dhcp_server }
    - { role: tftp }
    - { role: foreman }
    - { role: foreman_proxy }
