---
# This playbook deploys foreman together with passenger_apache and postgresql
# including foreman-proxy, tftp, dhcp and dns
- hosts: all
  become: true
  vars_files:
    - vars/example.yml
  roles:
    - { role: foreman }
